SELECT
    "Player"  as player_name
    ,"Nation" as nation
    ,"Pos"    as position
    ,"Squad"  as squad
    ,"Age"    as age
    ,"Born"   as born
    ,"90s"    as minute_div_90
    ,"CrdY"   as yellow_card
    ,"CrdR"   as red_card
    ,"2CrdY"  as second_yellow_card
    ,"Fls"    as foul_commited
    ,"Fld"    as foul_drawn
    ,"Off"    as offsides
    ,"Crs"    as crosses
    ,"Int"    as interceptions  
    ,"TklW"   as tackles_won
    ,"PKwon"  as pen_won
    ,"PKcon"  as pen_conceded
    ,"OG"     as own_goals
    ,"Recov"  as recoveries
    ,"Won" as aerial_won
    ,"Lost" as aerial_lost
    ,"Won_percentage" as aerial_won_percentage
FROM {{source('epl', 'miscellaneous_stat')}}    